### PR TITLE
Issue 6 add students field

### PR DESCRIPTION
**Pull request by JerryBao98**
Added a list of students to the classroom class.

### CODE REVIEW

**Review by galileokim — APPROVED** [review]
Good stuff.

**Review by destroyer8898 — APPROVED** [review]
beautiful

**Comment by AustinBao** [comment]
valid

**Comment by danielquzhao** [comment]
epic

**Review by alexxu06 — APPROVED** [review]

**Review by AustinBao — APPROVED** [review]

**Pull request merged**
